### ISSUE TITLE
Code timings

### ISSUE THREAD

**Issue by joshsia** [UBC-MDS/mds_525_group_15#5]
Please send how long it took to run the code here so that @aldojasb can easily compile the results in a table.

**Comment by joshsia** [comment]
Operating system: `macOS Big Sur Version 11.5.2`
RAM: `8GB`
Processor: `Apple M1`
Is SSD: `True`

1. Downloading data
```
CPU times: user 5.75 s, sys: 5.42 s, total: 11.2 s
Wall time: 1min 55s
```

2. Unzipping contents
```
CPU times: user 14.4 s, sys: 925 ms, total: 15.3 s
Wall time: 15.6 s
```

3. Combining data CSVs
```
CPU times: user 6min 47s, sys: 11.5 s, total: 6min 59s
Wall time: 7min 12s
```

4. EDA - Naive
```
CPU times: user 52.2 s, sys: 10.4 s, total: 1min 2s
Wall time: 1min 12s
```

5. EDA - `float32`
```
CPU times: user 52.1 s, sys: 10.7 s, total: 1min 2s
Wall time: 1min 10s
```

6. EDA - Loading required columns only
```
CPU times: user 42.7 s, sys: 7.13 s, total: 49.9 s
Wall time: 54.5 s
```

7. EDA - `float32` and loading required columns
```
CPU times: user 42.7 s, sys: 6.72 s, total: 49.4 s
Wall time: 53.6 s
```

**Comment by aldojasb** [comment]
Thanks Josh! I'm starting this step right now. Thanks!

**Comment by arijeetchatterjee** [comment]
Operating system: `macOS Big Sur Version 11.6`
RAM: `8GB`
Processor: `Apple M1`
Is SSD: `True`

1. Downloading data
```
CPU times: user 4.7 s, sys: 3.97 s, total: 8.67 s
Wall time: 2min 38s
```

2. Unzipping contents
```
CPU times: user 14.9 s, sys: 1.06 s, total: 15.9 s
Wall time: 16.7 s
```

3. Combining data CSVs
```
CPU times: user 9min 7s, sys: 11.5 s, total: 9min 19s
Wall time: 9min 26s
```

4. EDA - Naive
```
CPU times: user 49.5 s, sys: 11.1 s, total: 1min
Wall time: 1min 12s
```

5. EDA - `float32`
```
CPU times: user 49.4 s, sys: 10.3 s, total: 59.7 s
Wall time: 1min 8s
```

6. EDA - Loading required columns only
```
CPU times: user 40.6 s, sys: 7.62 s, total: 48.2 s
Wall time: 54.7 s
```

7. EDA - `float32` and loading required columns
```
CPU times: user 40.1 s, sys: 7.66 s, total: 47.8 s
Wall time: 54.2 s
```
